# BOOK, AUTHOR, BOOK_SALES
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK B
LEFT JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
LEFT JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

