# 대장균 개체의 ID(ID)와 자식의 수(CHILD_COUNT)를 출력
# 자식이 없다면 자식의 수는 0으로 출력
# 개체의 ID 에 대해 오름차순 정렬해주세요.

SELECT A.ID, IFNULL(B.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA A
LEFT JOIN 
    (SELECT PARENT_ID, COUNT(PARENT_ID) AS CHILD_COUNT
     FROM ECOLI_DATA 
     WHERE PARENT_ID IS NOT NULL 
     GROUP BY PARENT_ID) B
 ON A.ID = B.PARENT_ID
 ORDER BY A.ID ASC;
 