SELECT A.ID, 
    CASE B.등분
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH' 
        WHEN 3 THEN 'MEDIUM' 
        WHEN 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_DATA A
LEFT JOIN 
    (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS 등분 
     FROM ECOLI_DATA) AS B
ON A.ID = B.ID
ORDER BY A.ID;