# FROM(JOIN) -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY -> LIMIT
SELECT UGB.BOARD_ID, UGB.WRITER_ID, UGB.TITLE, UGB.PRICE,
    CASE UGB.STATUS
        WHEN 'SALE' THEN '판매중'
        WHEN 'RESERVED' THEN '예약중'
        ELSE '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD AS UGB
WHERE DATE_FORMAT(UGB.CREATED_DATE, "%Y-%m-%d") = "2022-10-05" 
ORDER BY UGB.BOARD_ID DESC;